using MongoDB.Bson;

namespace Dotnet.API.SDK.Utils;

public static class IdGenerator
{
    /// <summary>
    /// Generates a new Id
    /// </summary>
    /// <remarks>
    /// The Id is a <see cref="ObjectId"/> generated by MongoDb library
    /// </remarks>
    /// <returns>New Id</returns>
    public static string GenerateId()
    {
        ObjectId newId = ObjectId.GenerateNewId();
        return newId.ToString();
    }
}


/*
 * public static ObjectId GenerateNewId()
    {
        return GenerateNewId(GetTimestampFromDateTime(DateTime.UtcNow));
    }

/// <summary>
        /// Generates a new ObjectId with a unique value (with the given timestamp).
        /// </summary>
        /// <param name="timestamp">The timestamp component.</param>
        /// <returns>An ObjectId.</returns>
        public static ObjectId GenerateNewId(int timestamp)
        {
            int increment = Interlocked.Increment(ref __staticIncrement) & 0x00ffffff; // only use low order 3 bytes
            return Create(timestamp, __random, increment);
        }

private static ObjectId Create(int timestamp, long random, int increment)
        {
            if (random < 0 || random > 0xffffffffff)
            {
                throw new ArgumentOutOfRangeException(nameof(random), "The random value must be between 0 and 1099511627775 (it must fit in 5 bytes).");
            }
            if (increment < 0 || increment > 0xffffff)
            {
                throw new ArgumentOutOfRangeException(nameof(increment), "The increment value must be between 0 and 16777215 (it must fit in 3 bytes).");
            }

            var a = timestamp;
            var b = (int)(random >> 8); // first 4 bytes of random
            var c = (int)(random << 24) | increment; // 5th byte of random and 3 byte increment
            return new ObjectId(a, b, c);
        }

private static int GetTimestampFromDateTime(DateTime timestamp)
    {
        long num = (long)Math.Floor((BsonUtils.ToUniversalTime(timestamp) - BsonConstants.UnixEpoch).TotalSeconds);
        if (num < 0 || num > uint.MaxValue)
        {
            throw new ArgumentOutOfRangeException("timestamp");
        }

        return (int)num;
    }
 */